services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    volumes:
      - etcd_data:/etcd

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  pulsar:
    image: apachepulsar/pulsar:2.10.0
    container_name: milvus-pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus
    depends_on:
      - etcd
      - minio
      - pulsar
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MILVUS_DEPLOY_MODE: standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  etcd_data:
  minio_data:
  milvus_data:
